build: auto release functionality
afdesk/csv-report pull request #2
Opened 2023-04-03 12:05 UTC by malikovmm

2023-04-03 12:06 UTC, malikovmm commented
works the same as in scan2html. You need to change the version field in plugin.yaml

2023-04-04 11:47 UTC, afdesk commented
@malikovmm please, update this PR

2023-04-04 11:48 UTC, afdesk requested changes

2023-04-04 11:48 UTC, afdesk commented on src/template.go
this is old file

2023-04-06 07:03 UTC, afdesk approved these changes

2023-04-06 07:04 UTC, merged

2023-04-06 07:04 UTC, afdesk commented
thanks